const IntangibleFactors = {

    coreProductFactors : [
        "coreBenefit",
        "features",
        "quality",
        "materials",
        "packaging",
        "design",
        "price",
        "accessibility",
        "performance",
        "efficacy",
        "safety",
        "innovation",
        "environmentFriendly",
        "savingTime",
        "ingredients",
        "trust",
        "technology",
        "e-shop",
        "variety",
        "origin",
        "aesthetics",
    ],

    relatedServiceFactors : [
      "usability",
      "onlinePresence",
      "appsSoftware",
      "customerService",
      "onlineXP",
      "loyaltyRewards",
      "warranties",
      "trainings",
      "reliability",
      "afterSalesSupport",
      "delivery",
      "maintenance",
      "returns",
      "convenience",
      "demos",
      "exclusiveness",
      "automation",
      "communities",
      "content",
      "enablingFunction"
    ],

    intangibleFactors : [
        "brandImage",
        "customerExperience",
        "ethics",
        "onlineReviews",
        "status",
        "reputation",
        "socialInclusion",
        "events",
        "positiveEmotions",
        "customization",
        "fun",
        "atmospherics",
        "fashion",
        "influencers",
        "adventure",
        "health",
        "freedom",
        "refreshment",
        "selfActualization",
        "newness"
    ]
};

export { IntangibleFactors };
